### ISSUE TITLE
Error in instructions?

### ISSUE THREAD

**Issue by jackfruh** [jumbojett/OpenID-Connect-PHP#104]
Hi, the instructions say to **`require '/vendor/autoload.php';`**

This assumes your project is on the root of a drive and returns an error if not:
`Fatal error: require(): Failed opening required '/vendor/autoload.php' `

**Comment by jumbojett** [comment]
@jackfruh you'll need to install composer. https://getcomposer.org/doc/01-basic-usage.md
`composer init` in the base root of your project.

**Comment by jackfruh** [comment]
I used composer to install the package, so I think composer is ok?

See
-Folder structure (top left)
-Code (top right)
-Error (bottom)
![2017-11-11_11-25-34](https://user-images.githubusercontent.com/334880/32691900-812f8090-c6d4-11e7-9732-8df1010ea595.png)

If I remove the leading slash, the error goes away:
![2017-11-11_11-34-35](https://user-images.githubusercontent.com/334880/32691906-8b15af94-c6d4-11e7-8705-83baa37693d9.png)

I feel like even with this, I must be doing something wrong as the next step in the instructions is to add this line of code
 `use Jumbojett\OpenIDConnectClient;`
but PHPStorm is flagging the namespace as invalid, and the OpenIDConnectClient class isn't found:
![2017-11-11_11-40-33](https://user-images.githubusercontent.com/334880/32691944-3b744288-c6d5-11e7-94b2-d6e4f945a27a.png)

If this is something you'd have time to interactively troubleshoot, I'd gladly pay you for your time.

**Comment by jumbojett** [comment]
@jackfruh Have you tried `require __DIR__ . '/vendor/autoload.php';` ? It could be paths issue.

**Comment by jackfruh** [comment]
I did try that and it got past the path issue, but still couldn't find the class.

**Comment by jumbojett** [comment]
@jackfruh you might be using an old package. Try this:

```
# Tell composer to use the github repo for this lib
composer config repositories.repo-name vcs https://github.com/jumbojett/OpenID-Connect-PHP.git
# Get the latest from github
composer require jumbojett/openid-connect-php:dev-master
```

I hope this solves the issue!

**Comment by jackfruh** [comment]
Thanks! use Jumbojett\OpenIDConnectClient; is no longer flagging as an error in PHPStorm, so things are looking up!

**Comment by jumbojett** [comment]
@jackfruh Glad to hear! I encourage you submit a PR with changes to the README if you think anything needs clarification.
