### ISSUE TITLE
Unable to verify JWT claims in /var/www/html/mw/vendor/jumbojett/openid-connect-php/OpenIDConnectClient.php:281

### ISSUE THREAD

**Issue by Ralle75** [jumbojett/OpenID-Connect-PHP#109]
Hello,

i have the problem see above.
 [This](https://github.com/jumbojett/OpenID-Connect-PHP/issues/44) doesn't help, I have no trailing slash in my url
 I get a logon form from my Identity Server, and then I get this error

`[DBConnection] Wikimedia\Rdbms\LoadBalancer::openConnection: calling initLB() before first connection.
[DBConnection] Connected to database 0 at 'localhost'.
[session] Session "s1kesl4pef5o5aevd20t64h2m1qlahfd" requested without UserID cookie
OpenIDConnectClientException: Unable to verify JWT claims in /var/www/html/mw/vendor/jumbojett/openid-connect-php/OpenIDConnectClient.php:281
Stack trace:
#0 /var/www/html/mw/extensions/OpenIDConnect/OpenIDConnect.class.php(151): OpenIDConnectClient->authenticate()
#1 /var/www/html/mw/extensions/PluggableAuth/PluggableAuthLogin.php(46): OpenIDConnect->authenticate(NULL, NULL, NULL, NULL, NULL)
#2 /var/www/html/mw/includes/specialpage/SpecialPage.php(522): PluggableAuthLogin->execute(NULL)
#3 /var/www/html/mw/includes/specialpage/SpecialPageFactory.php(578): SpecialPage->run(NULL)
#4 /var/www/html/mw/includes/MediaWiki.php(287): SpecialPageFactory::executePath(Object(Title), Object(RequestContext))
#5 /var/www/html/mw/includes/MediaWiki.php(862): MediaWiki->performRequest()
#6 /var/www/html/mw/includes/MediaWiki.php(523): MediaWiki->main()
#7 /var/www/html/mw/index.php(43): MediaWiki->run()
#8 {main}`

my setup:
wso2 is 5.3.0
mediawiki 1.29
PluggableAuth 4.0
OpenID Connect 4.0 
and jumbojett/openid-connect-php 0.3.0

LocalSettings:
`$wgOpenIDConnect_Config['https://identity_server_fqdn/oauth2/oidcdiscovery'] = [
    'clientID' => 'ieY3KuRxxxxxxxxxxxxx',
    'clientsecret' => '2pSxxxxxxxxxxxxx',
    'scope' => [ 'openid', 'email', 'profile' ]
];`

Callback URL: https://wiki_server_fqdn/mw/index.php/Spezial:PluggableAuthLogin

any suggestions?

thx

**Comment by jumbojett** [comment]
> /var/www/html/mw/vendor/jumbojett/openid-connect-php/OpenIDConnectClient.php:281

@Ralle75 This is a security check. Set your debugger here and find out what doesn't match and correct the settings.

**Comment by Ralle75** [comment]
sorry but what do you mean with set you debugger here?

**Comment by jumbojett** [comment]
@Ralle75 If you have a PHP env with a debugger set a breakpoint here and examine the conditions. https://github.com/jumbojett/OpenID-Connect-PHP/blob/master/src/OpenIDConnectClient.php#L747

Alternatively, you could alter the code to help troubleshoot.

```
/* Begin Debug */
print_r($claims);
if (!($claims->iss == $this->getProviderURL()) print "check 1 failing";
// etc...
/* End Debug */
        return (($claims->iss == $this->getProviderURL())
            && (($claims->aud == $this->clientID) || (in_array($this->clientID, $claims->aud)))
            && ($claims->nonce == $this->getNonce())
            && ( !isset($claims->exp) || $claims->exp >= time())
            && ( !isset($claims->nbf) || $claims->nbf <= time())
            && ( !isset($claims->at_hash) || $claims->at_hash == $expecte_at_hash )
```

Make sense?

**Comment by Ralle75** [comment]
there is a difference between iss (https://server_fqdn:443/oauth2/token) and ProviderURL (https://server_fqdn:443/oauth2/oidcdiscovery)

**Comment by JanOonk** [comment]
Had the same problem on my dev PC (Windows 10 with WAMP), it worked on my production server (Linux/Nginx). This line failed on me in `OpenIDConnectClient.php`:
`( !isset($claims->nbf) || $claims->nbf <= time())`

I "fixed" it by adding 2:
`( !isset($claims->nbf) || $claims->nbf <= time()+2)`
