### ISSUE TITLE
Is there a specific reason to force version 2.0.1 of phpseclib?

### ISSUE THREAD

**Issue by ivanPrunier** [jumbojett/OpenID-Connect-PHP#111]
Hi,

I currently have phpseclib required in my dependencies, with the 2.0.9 version as a minimum. Is there any reason your package requires the version 2.0.1 of phpseclib specifically?

Thanks!

**Comment by c4l3b** [comment]
https://github.com/jumbojett/OpenID-Connect-PHP/pull/144
