### ISSUE TITLE
Compatibility with GPLv2 Software

### ISSUE THREAD

**Issue by NicolasToussaint** [jumbojett/OpenID-Connect-PHP#113]
Hello Michael,

I am setting up authentication using your OpenID-Connect-PHP library in the [fossology](https://github.com/fossology/fossology) solution.
However, I am blocked since Fossology is GPLv2, which is not compatible with ApacheV2.

Would you possibly consider adding (for example) a BSD license so that it could be used along GPLv2 products ?

This would be of great help, thanks,

Nicolas

**Comment by jumbojett** [comment]
Hi Nicolas! Thanks for reaching out. I'd def consider it. Are there any caveats in doing this? (cc: @jricher )

**Comment by NicolasToussaint** [comment]
Michael,
Thanks for considering it !

To my understanding (noting, that IANAL), the specific thing that makes Apachev2 not compatible with GPLv2 is the handling of patents (I think you agree to grant copyright license to anyone who receives the code with ApacheV2).

In fact, Fossology is GPLv2, so for me a dual license with either [BSD3](https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD) (more permissive), or [GPLv2](https://www.gnu.org/licenses/license-list.en.html#GPLv2) (more restrictive) -or many others- would be great.

**Comment by jumbojett** [comment]
> so for me a dual license with either BSD3 (more permissive), or GPLv2 (more restrictive) -or many others- would be great.

@NicolasToussaint Thanks for the detail! If there are no other concerns, would you like to submit a PR for this? _Add dual licensing via BSD3_ I'll be sure to review it as soon as possible.

**Comment by NicolasToussaint** [comment]
Hi @jumbojett ,

After internal discussion, it turns out that for you to accept a licence change, you would be supposed to obtain an agreement from all contributor to the project ... at least for the members who made significant contributions.
There seems to be about 30 contributors so that would mean a little bit of work to ask and obtain permission from them to add a BSD licence.

It would be great if you were up for that, but I totally understand if not !

Otherwise my alternatives are either package the library in a debian package so as to distribute separately, or use another library.

**Comment by kenguest** [comment]
Permission granted for anything I've done that got merged ;-)

**Comment by connerbw** [comment]
I looked at `fossology/LICENSE`

> This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, **or (at your option) any later version.**

The Free Software Foundation considers the Apache License, Version 2.0 to be a free software license, compatible with version 3 of the GPL. 

Wouldn't it be easier to simply upgrade your license to GPLv3 aka any later version?

**Comment by NicolasToussaint** [comment]
Hi @connerbw,
Thanks for looking and your suggestion ;
However, I'm afraid that changing Fossology is clearly not an option.

Anyhow, if anyone is interested in an external authentication mechanism in Fossology, we finally took another approach: we rely on Apache modules to handle the authentication and inject headers in the HTTP requests.
The feature is not pubhlished yet, since we still have to handle the logout feature & documentation...
