### ISSUE TITLE
Method requestResourceOwnerToken doesn't work without the header

### ISSUE THREAD

**Issue by BigTonni** [jumbojett/OpenID-Connect-PHP#114]
Hi!
Your library suits well in my project. Thanks! But when I use the method **requestResourceOwnerToken**, the request comes with an error. As it turned out, I need to add a header "Authorization: Basic" in the method. As in next method **requestTokens**. Then everything works.
When you tested this method, did you have an error? It may be worth adding the possibility that the person who uses this library can add their own headers outside this method?

**Comment by jumbojett** [comment]
Hi @BigTonni ! Even though it's not mentioned in the spec, that sounds logical. If I recall, this method was submitted by another user. Adding the header shouldn't break the flow for others. Do you mind giving it at first pass and submitting a PR?

**Comment by BigTonni** [comment]
Hi @jumbojett !
What is needed for this? Do I create a separate branch and push a commit with code changes for this method?

**Comment by jumbojett** [comment]
@BigTonni Pretty much! This guide should help. https://help.github.com/articles/creating-a-pull-request/

**Comment by BigTonni** [comment]
@jumbojett , share the rights for my account. I can not create a new branch for commits.

**Comment by lordelph** [comment]
@BigTonni you need to create your own fork first - see the section in the linked article

> If you don't have write access to the repository where you'd like to create a pull request, you must create a fork, or copy, of the repository first. For more information, see "Creating a pull request from a fork" and "About forks."

So, fork this repo, create a branch on your fork, push the branch to this repo.

**Comment by BigTonni** [comment]
@lordelph thank you! Ready.

**Comment by jumbojett** [comment]
Linking PR #115

**Comment by azmeuk** [comment]
Closed by #271
