### ISSUE TITLE
Back-Channel Logout

### ISSUE THREAD

**Issue by binary-sort** [jumbojett/OpenID-Connect-PHP#116]
Is back channel logout supported?

**Comment by jumbojett** [comment]
@binary-sort I don't believe so. Is this something we should consider?

**Comment by binary-sort** [comment]
I think you should consider supporting back channel logout.

You can get more information about it here: http://openid.net/specs/openid-connect-backchannel-1_0.html

**Comment by jumbojett** [comment]
Thanks for the link @binary-sort ! If you'd like to give it a pass and submit a PR. I'd be happy to review it!

**Comment by Ornias1993** [comment]
@jumbojett This is basically a must-have, because it makes this package unusable with multiple sites (as it is a huge security risk if users forget to logout in everyone of the sites they have opened)
