### ISSUE TITLE
The package 0.3.0 downloaded by default by composer does not work

### ISSUE THREAD

**Issue by JFLarvoire** [jumbojett/OpenID-Connect-PHP#117]
I had exactly the same issue as reported in bug #104.
And like for bug #104, this required updating the require instruction, AND downloading the latest dev package from GitHub to fix it.
So my point is that bug #104 should not have been closed:
1) The instructions on https://github.com/jumbojett/OpenID-Connect-PHP are indeed wrong, and it's necessary to do...
`require __DIR__ . '/vendor/autoload.php';`  
... as explained on composer doc: https://getcomposer.org/doc/01-basic-usage.md  
2) The jumbojett/OpenID-Connect-PHP package version 0.3.0 downloaded by composer from its default repositories does not work (at least in some cases like ours), and should be fixed.

**Comment by jumbojett** [comment]
@JFLarvoire thanks for the report. I just tagged a new release with the latest updates. Let me know if this fixes it!

**Comment by JFLarvoire** [comment]
This new version works well, thanks for the quick reply!
Just one minor thing: The README.md still contains the wrong instruction `require '/vendor/autoload.php';`.

**Comment by jumbojett** [comment]
Done 👍 Thanks for raising this issue @JFLarvoire !
