### ISSUE TITLE
$_SERVER['SERVER_NAME'] vulnerability

### ISSUE THREAD

**Issue by jedi58** [jumbojett/OpenID-Connect-PHP#119]
`$_SERVER['SERVER_NAME']` is populated based upon the value of `Host` sent in the request which means the `redirect_uri` in https://github.com/jumbojett/OpenID-Connect-PHP/blob/master/src/OpenIDConnectClient.php#L432
 can be modified to go to a different site. An example of this attack would be if a browser extension has been compromised.

**Comment by jumbojett** [comment]
@jedi58 a security check can be handled outside of the class. Ex:

```
if ($_SERVER['SERVER_NAME'] != $config['server_name']) {
    $_SERVER['SERVER_NAME'] = $config['server_name']
}
```

It's also important to note this code will not be used if the client specifies a redirect url. Does this address your concern? Would you recommend adding this to the README?

**Comment by jedi58** [comment]
That's a good point, it is better handled outside this - maybe a note in the README might be worthwhile to be safe
