### ISSUE TITLE
ADFS problem with example

### ISSUE THREAD

**Issue by d-sko** [jumbojett/OpenID-Connect-PHP#132]
Hi,

I've tried to authenticate against our ADFS 4.0 using the `client_example.php`. Authentication worked (it seems), but `$name` was empty, so I added `var_dump($oidc->requestUserInfo());` to see all contents of the userinfo. The result is this:
```
object(stdClass)#7 (1) { ["sub"]=> string(44) "GZlsnJmtb....[redacted]" }
```
What's wrong here? Am I missing something in the configuration on the ADFS side of things?

**Comment by d-sko** [comment]
Ah ok, got it with the implicit flow.

**Comment by jumbojett** [comment]
Thanks for the update @d-sko . Glad you were able to figure it out!

**Comment by d-sko** [comment]
@jumbojett yes, it was quite easy, nice simple library, thanks!

Just if someone tries the same: this is the complete OpenID-Connect  part:
```php
/* $cfgOidcHost is https://<fqdn of adfs host>/adfs
 * $cfgOidcClientId and $cfgOidcClientSecret contain the client id and -secret 
 * that you get in the application group setup on the ADFS-host
 */ 
$oidc = new \Jumbojett\OpenIDConnectClient($cfgOidcHost, $cfgOidcClientId, $cfgOidcClientSecret);
$oidc->setResponseTypes(['id_token']);
$oidc->addScope(['openid']);
$oidc->setAllowImplicitFlow(true);
$oidc->addAuthParam(['response_mode' => 'form_post']);
$oidc->authenticate();
$user = $oidc->getVerifiedClaims('unique_name');
```
`$user` will contain the windows username in the form `DOMAIN\username`.
