### ISSUE TITLE
ADFS implicit flow - get email?

### ISSUE THREAD

**Issue by d-sko** [jumbojett/OpenID-Connect-PHP#135]
Hi,

how can I get the email address of the user with the implicit flow?
I've added the `email` scope and checked it in the ADFS configuration but the response didn't change, still only `upn` and `unique_name`

```php
/* $cfgOidcHost is https://<fqdn of adfs host>/adfs
 * $cfgOidcClientId and $cfgOidcClientSecret contain the client id and -secret 
 * that you get in the application group setup on the ADFS-host
 */ 
$oidc = new \Jumbojett\OpenIDConnectClient($cfgOidcHost, $cfgOidcClientId, $cfgOidcClientSecret);
$oidc->setResponseTypes(['id_token']);
$oidc->addScope(['openid', 'email']); // << added email here
$oidc->setAllowImplicitFlow(true);
$oidc->addAuthParam(['response_mode' => 'form_post']);
$oidc->authenticate();
$claims= $oidc->getVerifiedClaims();
```
`$claims` still contains only 
```
aud
iss
iat
exp
authTime
nonce
sub
upn
uniqueName
sid
```

**Comment by jumbojett** [comment]
@d-sko I believe you're doing it the correct way. Have you verified your OIDC provider supports this? (Visit https://provider.url/.well-known/openid-configuration) Make sure _email_ is listed under _ claims_supported_ . If it isn't, then you won't be able to retrieve that attribute.

**Comment by jumbojett** [comment]
@baru Do you have any additional insight? (I know you submitted the ADFS PR a while back.)

**Comment by baru** [comment]
I can confirm that you are doing it the correct way.
getVerifiedClaims contains **all** claims from the JWT-Token, if the JWT-Token could be verified or **none** if the token could not be verified.
If the response doesn't change when you add email to the scope, that probably means that your provider is not including the email, even though you are requesting it.
Maybe this stackoverflow article applies: https://stackoverflow.com/questions/35295260/adfs-openid-connect-email-claim-and-external-adfs

**Comment by d-sko** [comment]
Thank you for your comments! 
@jumbojett: I've checked the _openid_configuration_ and _email_ is indeed __not__ listed under _claims_supported_.
@baru: thanks for the link, I'll have a look at this!

**Comment by d-sko** [comment]
I got it! Found this very helpful article: https://blogs.technet.microsoft.com/piameruo/2017/10/22/custom_idtoken/

Short version: I've checked _allatclaims_ in the permitted scopes list in the application configuration in the ADFS management console and added a Issuance Transform rule with all attributes I need and now it's working.
