### ISSUE TITLE
OneLogin: The provider authorization_endpoint could not be fetched

### ISSUE THREAD

**Issue by albertStaalburger** [jumbojett/OpenID-Connect-PHP#136]
I am trying to get Example 1 working.
I am using OneLogin as Idp and have entered/set up the required Ids as well as keys.
The OneLogin provider url is:[https://openid-connect-eu.onelogin.com/oidc/.well-known/openid-configuration](https://openid-connect-eu.onelogin.com/oidc/.well-known/openid-configuration)

The config returned in the link above does have an `authorization_endpoint`, however whenever I try to log in I get:

> The provider authorization_endpoint could not be fetched

Has anyone used this with OneLogin before?
Any reason why I might be getting this?

**Comment by jumbojett** [comment]
@albertStaalburger given what you've stated, your provider should be set to `https://openid-connect-eu.onelogin.com/oidc`. Can you confirm this is the case?

**Comment by albertStaalburger** [comment]
Thank you. Seems like such a trivial question looking at the answer.
This sorted the `provider` issue.

Getting `invalid_client` error now.
Will double check my client id and secret.

**Comment by albertStaalburger** [comment]
`invalid_client` was caused by not using the correct provider url, had to remove the `-eu`.
Related to getting Example 1 going, the response says that:

> client_secret must be provided in the body

Digging through the code I see that I receive the code, but the `requestTokens` function throws an error.
It puts the client secret in the header...looks like the endpoint is expecting it in the body.

**Comment by albertStaalburger** [comment]
I narrowed the issue down to the `requestTokens` function, specifically the `unset($token_params['client_secret']);`

Not unsetting the `client_secret` allowed my app to authenticate.
I am new to the OIDC arena...
Am I opening myself up to issues here, what is the reason for just unsetting the `client_secret`?

**Comment by jumbojett** [comment]
@albertStaalburger are you using client_secret_basic? 

> I narrowed the issue down to the requestTokens function, specifically the unset($token_params['client_secret']);

The code you're referring to unsets it because the client secret gets encoded in a header. Closing for now. Feel free to reopen if needed!
