### ISSUE TITLE
Assigning the return value of new by reference is deprecated : /usr/local/php5.4/share/pear/Crypt/RSA.php 232

### ISSUE THREAD

**Issue by kaboume** [jumbojett/OpenID-Connect-PHP#141]
Hi,
When the OpenIdProvider redirects the user agent on the callback url, i have this PHP error : 
`Assigning the return value of new by reference is deprecated|/usr/local/php5.4/share/pear/Crypt/RSA.php|232`
I'm using PHP 5.6.
Do you have any idea to solve the problem ?
Thanks.

**Comment by jumbojett** [comment]
Hey @kaboume ! Are you getting an ERROR or a NOTICE? Check out this stackoverflow topic for how to silence NOTICES. (https://stackoverflow.com/questions/2867057/how-do-i-turn-off-php-notices)

**Comment by jumbojett** [comment]
Closing for now. Feel free to re-open if needed.
