### ISSUE TITLE
Refactor library to function as standalone plugin

### ISSUE THREAD

**Issue by bobvandevijver** [jumbojett/OpenID-Connect-PHP#147]
Currently, this library can only be used by including the single source file in the application, directly loading global function which are never required in global scope. 

I think this library can benefit from some decent object oriented design, so that it can easily be reused by other libraries such as Symfony library. 

Currently, I've adapted this library to fit directly in my library, but are you interested to have it backported here?

**Comment by bobvandevijver** [comment]
My current source is not yet published, but I have just placed one of the source files in this gist: https://gist.github.com/bobvandevijver/8a9e7540f75c898ad02696ce7629002e. 

I only use small parts of the library for now, but I hope this gives a general idea.

**Comment by athanasius-kircher** [comment]
I have forked this library to start a proposal, for a library that should be easier to be integrated into different frameworks. I moved restructured the library itself and used different dependencies to let this library focus on oauth aspects and move typical framework functions to dependencies. It would be a breaking change but adoption would not much steps.
I have not finished it totally, but if anyone is interested in moving forward, I would proceed.

**Comment by jumbojett** [comment]
@athanasius-kircher wow! This looks really good. I've been wrestling with the decision to refactor for a while. There are so many well-structured libraries out there centric to OpenID Connect. (https://github.com/thephpleague) This project differs (for or for worse) in the fact that it's small, and single file. If we did go with your proposal, what other factors would set us apart from these libraries?

**Comment by heinebold** [comment]
"There are so many well-structured libraries out there centric to OpenID Connect"
I cannot find anything that actually implements not just OAuth 2 but OpenID Connect, and is at least somewhat maintained. Do you have examples for me? The League seems to have onle OAuth.

**Comment by bobvandevijver** [comment]
I've just released my adaptation of this project, which refactor the classes and makes them available in a very simple Symfony bundle. See https://github.com/Drenso/symfony-oidc! Many thanks to @jumbojett for this repository.

**Comment by dlecan** [comment]
Would it be possible to merge these 2 projects?
This one support PKCE (and not the other), but the other is better organized and prepared for Symfony (and not this one)

Thank you

**Comment by bobvandevijver** [comment]
I would actually love to be able to consume this library directly via a composer dependency in the symfony-oidc bundle. With the go-ahead of @jumbojett I could refactor this library into separate classes as I did in the bundle, so that can be released as a v1 maybe?
