### ISSUE TITLE
CakePHP CSRF Token Mismatch

### ISSUE THREAD

**Issue by rabiulislamanik** [jumbojett/OpenID-Connect-PHP#173]
I am trying to authenticate using implicit flow.

```     
      $oidc = new OpenIDConnectClient('http://localhost:8080/auth/realms/myrealm',
                                'my-client',
                                '1441552b-4b95-4b3b-aab7-a6437e61d7c9');
      $oidc->setCertPath('http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/certs');
      $oidc->setRedirectUrl('http://localhost:8765/test');
      $oidc->setResponseTypes(['id_token']);
      $oidc->addScope(['email']);
      $oidc->addAuthParam(['response_mode' => 'form_post']);
      $oidc->setAllowImplicitFlow(true);
      $oidc->authenticate();
      $claims= $oidc->getVerifiedClaims();
```
I am getting this error - 
`CSRF token mismatch.
Cake\Http\Exception\InvalidCsrfTokenException`

By the way, it works fine if i don't use this line `$oidc->addAuthParam(['response_mode' => 'form_post']);`

**Comment by stellarbear** [comment]
Sorry for being more than 2 years late.
When you are using POST (form_post mode implies this), you are expected to have a CSRF token validation.

So there are 2 ways to solve this problem:
1. Move your route from web.php to api.php (where verification won't happen)
2. Exclude your particular route from verification at VerifyCsrfToken class, for example:

`
class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        'http://localhost:3000/callback',
    ];
}
`

**Comment by DeepDiver1975** [comment]
in any case nothing which is to be fixed by this library -> close
