### ISSUE TITLE
Problems using Google as the provider

### ISSUE THREAD

**Issue by mhauslerArcweb** [jumbojett/OpenID-Connect-PHP#18]
I'm trying to use this library to log into a Mediawiki instance using its OpenID Connect sign-in plugin and am using Google as the provider.  I use the Google Developer's Console to obtain the Client ID and Client Secret from the project.  Unfortunately, I run into a few issues that require manual changes to the code:

1.  Nonce values are not accepted by Google's servers, so I need to comment out the nonce code or else the Google servers will return an error.

2.  The log in sometimes will work, while other times, there is an issue with the RSA key verification and the login will fail.  I'm not sure if it's a problem with Google or if it's a problem with the Mediawiki's server's security.  I don't know much about how encryption works, so I'm very lost.  It might be caused by the disabled noncing I mentioned above.  I'm also considering if it's a problem with proxies, but again, I don't know for sure anything.  If you know anything that can help with this, or need certain information to help, let me know.

**Comment by jumbojett** [comment]
1. That's good to know. If the current draft of OpenID Connect does not require `nonce's` then this needs to be reflected accordingly.
2. I'm curious, could you revert to @0214020e8dabfd and see if it solves the issue? @jdreed might be able to provide more insight into key verification.

**Comment by mhauslerArcweb** [comment]
Would reverting to that commit compromise security?  If so, how?

**Comment by jdreed** [comment]
I haven't used Google's OpenID Connect, so I can't speak to that.  As I understand it from reading it, the nonce is in fact optional.  If present and accepted by the server, the client must verify it, but I can't find anything in the draft requiring it to be present.

I have limited experience with key verification -- I've only done RSA with PKCS15 signature key verification, because that's all my local server supports.  My fallback for troubleshooting signature verification is to do it by hand.  If it's failing part of the time, I'd look at the Base64 URL decoding that you're doing.  Remember that Base64URL is NOT regular Base64 (I got bitten by this more than once).  The alphabet differs in the last two characters, and padding is whitespace, not '=".  See b64url2b64() in  https://github.com/jdreed/mit-oidc-examples/blob/master/php/jwt.php for an example of how to prepare base64url-encoded data to be decoded.  Also ensure that the message is not being modified by anything else along the way, particularly anything that's decoding and re-encoding it.

**Comment by mhauslerArcweb** [comment]
The issue, after looking at some debug logs, seems to have something to do with the signature it's checking having about 20 slashes in the middle of it when converted to a readable format (http://davidwalsh.name/php-serialize-unserialize-issues).  I believe this may be part of the issue.

**Comment by jdreed** [comment]
That sure sounds like base64 vs base64url encoding.  In base64, '+' and '/' are valid characters, but in base64url (which an OpenID Connect server should be using), they are replaced with '-' and '_' respectively.  PHP does not support the URL-safe version of base64 natively, and anything which attempts to perform regular base64 encoding/decoding on base64url-encoded data will eventually fail.

**Comment by jricher** [comment]
The spec does not require that a client send a nonce, however it requires that if the client sends a nonce then the server MUST return it in the ID token. Google's in error here, and people should probably file a bug with them until they fix it.

**Comment by mhauslerArcweb** [comment]
What's very strange about it is that the log in works fine in the morning, but never in the afternoon, and I have no leads as to what could cause that.

**Comment by laureek** [comment]
I am also having this issue.  Is the current fix to comment out the nonce code?

**Comment by jumbojett** [comment]
@laureek - If you are using it with Google as the provider, then "yes."

**Comment by mhauslerArcweb** [comment]
As an update, I have the suspicion that the error only happening after noon has something to do with whether the encryption keys are seeded based on military time or not.  In the morning where military time is the same as regular time, the decrypted values are the same, but when noon hits, one changes and the other doesn't.

I was also wondering if using refresh tokens will be a future feature.  After disabling the noncing and the weird encryption error, people can log in, but we are continuously logged out after 30 minutes of not going to another page and it's rather annoying when you lose your work on a page.  Refresh tokens aren't mentioned directly in the code, but if the procedure is the same as regular authentication, the reason might be because it's just implicit.

**Comment by alexedelsburg** [comment]
I've issued a pull request, https://github.com/jumbojett/OpenID-Connect-PHP/pull/20, that I believe fixes this issue.

**Comment by jumbojett** [comment]
Thanks @alexedelsburg!

@jdreed this change corresponds to some of your previous efforts. Preferably I'd like for you to test #20 and merge upon approval. Would that work?

**Comment by alexedelsburg** [comment]
My pleasure :smile: 

I've got a potentially related/useless PR to share as well: a toggle for the nonce. I actually left the nonce on after making this change and things seem to work for me, hence why it might be useless.

**Comment by jumbojett** [comment]
This issue should be resolved with the latest commit.
