### ISSUE TITLE
connecting identify server

### ISSUE THREAD

**Issue by ghost** [jumbojett/OpenID-Connect-PHP#212]
I'm trying to connect to identify server with settings 
```
Scope : offline_access
Response type: code id_token
DefaultScheme = “Cookie”
```

Error I'm getting:

> Sorry, there was an error : unauthorized_client
Invalid grant type for client

My code

```
$issuer = 'issuer';
$cid = 'clientid';
$secret = 'clientsecret';
$oidc = new Jumbojett\OpenIDConnectClient($issuer, $cid, $secret);
$oidc->addScope(array('openid', 'offline_access'));
$oidc->authenticate();
$oidc->requestUserInfo('sub');
$user = $oidc->requestUserInfo();
session_start();
$_SESSION['user'] = $user;

```
Why causes the error? Thanks!

**Comment by mgh9** [comment]
I have a same problem, did you find the solution?

**Comment by mgh9** [comment]
I'm trying to use hybrid flow, setting `$oidc->setResponseTypes(array('code','id_token'));` solved my problem
