### ISSUE TITLE
call Graph API for users in AD

### ISSUE THREAD

**Issue by aliogul** [jumbojett/OpenID-Connect-PHP#214]
Hello,

I want to implement a search field where users type a name in our organisation and get the list from Azure Directory 
I assume I need to call this https://graph.microsoft.com/v1.0/users?$filter=startswith(displayName,'ali')

What is the best way to do this using jumbojett so the user first login then is able to search?

The AD is managed by my organisation, can't really play with.

**Comment by JuliusPC** [comment]
You first need to obtain authorization from the user (this can be done by this library) via OAuth 2.0 and OpenID Connect:

~~~php
$oidc = new OpenIDConnectClient(
  'https://idp.example.org',
  'client_id',
  'client_secret'
);

// maybe you need to add additional scopes by calling `addScope` before authenticating
$oidc->authenticate();

// get access token and safe it for following requests:
$oidc->getAccessToken();

// Use the obtained access token to access the graph api.
~~~

Notice that you need to consult the API’s docs about which OAuth scopes you need and how long the access token ist valid. In case you need a new one, you may use refresh token or call another time `authenticate()`.

**Comment by DeepDiver1975** [comment]
Question has been answered. Support of msgraph in this library is out of scope from my pov
