### ISSUE TITLE
How to check if user is already logged in?

### ISSUE THREAD

**Issue by adi-ads** [jumbojett/OpenID-Connect-PHP#22]
id_token and claims expiration are not stored so how to check if the user is already logged in or not?

**Comment by jumbojett** [comment]
@adi-ads I'm not entirely sure if this answers your question.

Whether the user is "logged in" or "not" is determined by your application. The OpenID Connect library simply provides a way to get the identity of the user through a provider. This normally happens at an initial login. Ideally your app shouldn't have a persistent connection to the OIDC server. (i.e. monitoring the identity server for changes and refreshing tokens.)

See the Wordpress plugin for a real world example: https://github.com/jumbojett/Wordpress-OpenID-Connect-Login

Does this answer your question?

**Comment by adi-ads** [comment]
Yep it does

Did a sample here as well - 
https://github.com/adi-ads/connect-app-php

Using a auth server I am helping build - 
https://github.com/christiansmith/anvil-connect

Do drop by and have a look at our auth server, seems to work well with your client.

Cheers

**Comment by jumbojett** [comment]
@adi-ads very neat! Thanks for pointing me towards those projects.

I like the concept of anvil. I'm wondering if it could be taken a step further and built into a firewall like Ubuntu UFW. Anyways, that's my food for a thought. :)

**Comment by adi-ads** [comment]
Good idea, will definitely explore that. cheers!

**Comment by halilibrahim95** [comment]
@jumbojett Hello, I successfully implement log in and log out using your module. After log-in, I manage the session of the logged-in user, the question is what if user logged out auth server? Should I logged out him? Is it OK to monitor?

**Comment by mgh9** [comment]
> @jumbojett Hello, I successfully implement log in and log out using your module. After log-in, I manage the session of the logged-in user, the question is what if user logged out auth server? Should I logged out him? Is it OK to monitor?

Could you please share your source? thanks
