### ISSUE TITLE
What authParams can I add?

### ISSUE THREAD

**Issue by piyushgupta95** [jumbojett/OpenID-Connect-PHP#232]
Pardon me if this question sounds silly, but what is 'authParams' used for? I would like to study more about it

Also, are there examples or list of optional parameters that I can set through `addAuthParam($var)` function? One that I know of is `'response_mode' => 'form_post'` from the example.

Thanks.

**Comment by jumbojett** [comment]
@piyushgupta95 these are used during the auth request. See https://github.com/jumbojett/OpenID-Connect-PHP/blob/9f15504105640b03277d7174b62fbfc0f5e608ab/src/OpenIDConnectClient.php#L624

You can find a list here:
https://openid.net/specs/openid-connect-basic-1_0.html#RequestParameters

Hope this helps!
