### ISSUE TITLE
Intercept authenticate() or return state before redirect

### ISSUE THREAD

**Issue by tsvsj** [jumbojett/OpenID-Connect-PHP#234]
Hi,

I'm currently playing around with this great framework. In general everything is working fine, if I configure a single provider statically. However, I would like to have several provider configurations and let the user choose the preferred provider. Therefore I'm saving the provider configuration at a secure space instead of saving vars for the provider configuration statically. Issuing the OIDC auth request is working fine, but I'm struggling around when it comes to find the correct provider for code validation.

To be more precise about my issue: After the authentication request is sent to the provider, the authentication is done successfully and the provider redirects me back to my redirect_url (same script as the login). In the request I only have the parameters `state` and `code`. Unfortunately I can't derive the provider from those parameters.

I thought of saving the state somewhere, along with a unique identifier for the provider. Unfortunately I can't intercept `authenticate()` to get `state`, before the redirect is sent to the client.

Any ideas how I could intercept the `authenticate()` function to get the state or is there a way to save the state in the filesystem, which I wasn't able to find?

Thanks for your help and this great work.

**Comment by cicalese** [comment]
You can use `getProviderURL()` after `authenticate` returns to get the provider to which the authentication request was sent.

**Comment by tsvsj** [comment]
Isn't that too late? For now I check the result of `authenticate()` to decide whether the authentication was successful or not. If I would skip that test, how would I check for successful authentication?

**Comment by tsvsj** [comment]
I've tried that, but as assumed it doesn't work. `authenticate()` triggers the redirect, before the next line of code is executed.

Anymore ideas instead of rewriting the class?

**Comment by tsvsj** [comment]
I've found a solution. While going through the code, I realized, that the state is stored in `$_SESSION`. So I'm just saving the provider URL in the session as well and can look for the correct provider configuration by URL, if the client returns to provide the `code`.
