### ISSUE TITLE
Help with Finding Whether User Is Authenticated

### ISSUE THREAD

**Issue by slauensc** [jumbojett/OpenID-Connect-PHP#247]
We are trying to use OpenID-Connect-PHP for SSO with Oracle IDCS as the Authorization Server.  There are three separate websites that will be doing SSO with IDCS.

This is all fairly new to me, and I'm having a hard time understanding if or how I can use this library to check for whether a user is already authenticated on the Authorization Server.

I have the OpenID-Connect-PHP library installed and working with a simple stub program, and am able to use it to login via IDCS, retrieve user information, and logout.

The scenario I'm having problems with is this:
Let's say that a user comes to the main landing page on our website.  If they are already logged in via SSO/IDCS I want to automatically redirect them to a sub-page.  This part is working fine, by calling the authentication function in the library, which passes me back the information telling me they are authenticated.  

However, if they are not yet logged in via SSO/IDCS, I want to show them a login button on the page, which, when clicked, will call the authentication function through the library and IDCS.  

I cannot use a call to the authenticate function in the library to check for whether they are logged in, since it will bring them to the IDCS login page if they are not logged in.  This isn't what I want to do yet.  I simply want to know if they are already authenticated.  If not, show them a login button, which, when clicked, will call the authenticate function and bring them to the login screen.

I've seen some other discussions about tracking this using a session on our website.  However, this won't necessarily work either, since the user may have authenticated already via one of the other two websites using this SSO capability.  So, in that case, they would appear as authenticated in IDCS, but would not yet have a session for our website.

Hopefully that all makes sense.  I guess, in a nutshell, what I'm asking is this:  Is there a way to check if a user has been authenticated using this library, without having the Authorization server show the login page if the user is not yet authenticated?

**Comment by Sebi2020** [comment]
If you can check, that an user is already authenticated to IDCS (how do you do that?!) what is the issue with just redirecting through the authenticate() call? Because the user is already authenticated to IDCS (e.g. have a session with the authorization server), IDCS would redirect the user back to your application without showing a login prompt.

> So, in that case, they would appear as authenticated in IDCS, but would not yet have a session for our website.
And that's good, because it's the whole idea behind SSO.

I'm a little confused about how you can manage to check the authentication status without redirecting the user to the authorization server.

> . This part is working fine, by calling the authentication function in the library, which passes me back the information telling me they are authenticated.
As a user I would be more confused about being automatically redirected to another server without pressing a login button.

**Comment by slauensc** [comment]
Thank you for providing those links.  They look promising.  We'll review them and try to make use of them to accomplish what we need.

**Comment by slauensc** [comment]
Using the "none" option for the "prompt" request parameter seems to give us what we need.

$addtlauth = array("prompt"=>"none");
$oidc->addAuthParam($addtlauth);
$oidc->authenticate();

When the authenticate() function is called, and the user is not yet authenticated, our IDCS Authorization Server returns a "login_required" error, which, per the OIDC spec, is what is expected.

PHP Fatal error:  Uncaught exception 'Jumbojett\\OpenIDConnectClientException' with message 'Error: login_required Description: Login_required for client:

Now, it should just be a matter of trapping the error, and taking appropriate action.
