### ISSUE TITLE
Undefined index: openid_connect_state

### ISSUE THREAD

**Issue by michug** [jumbojett/OpenID-Connect-PHP#255]
I have a backend project (Laravel php)
And a frontend project (Vue js)

I created an authenticate function in a controller:
```
$issuer = 'https://broker.netid.de';
$cid = 'myClientId';
$secret = 'myClientSecret';
$oidc = new OpenIDConnectClient($issuer, $cid, $secret);

$oidc->authenticate();
```
The frontend sends a request to the backend that is handled by the authenticate function specified above.
The backend answers with a redirect to the authorize endpoint, the front end catches it and redirects to the url ( by setting the window.location)
The user logs in and then the a request is sent to the redirect_uri with the authorization code.
And I get the error "Undefined index: openid_connect_state"

However, when I hit the Controller authenticate function directly:
he backend answers with a redirect to the authorize endpoint, the front end catches it and redirects to the url
The user logs in and then the a request is sent to the redirect_uri with the authorization code.
And then requests a token and everything works fine.

**Comment by JuliusPC** [comment]
Pull Request #251 would fix this. Because I don’t want to wait until jumbojett reacts, I [forked this library](https://github.com/JuliusPC/OpenID-Connect-PHP) and added this functionality. I will add some other improvements in the future.

**Comment by azmeuk** [comment]
#251 is merged
