### ISSUE TITLE
Stateless support

### ISSUE THREAD

**Issue by Bilge** [jumbojett/OpenID-Connect-PHP#263]
This library hides the fact that session support is required. More importantly, session support should not be required and it should be possible to operate in a stateless mode.

**Comment by JuliusPC** [comment]
How would you implement this?

**Comment by Bilge** [comment]
One-way hashes.

**Comment by JuliusPC** [comment]
Can you provide some pseudo code for the flow?

**Comment by Bilge** [comment]
No, I declined to use the library in the end.

**Comment by JuliusPC** [comment]
Aha.
