### ISSUE TITLE
composer.json specifies the paragonie/random_compat dependency twice

### ISSUE THREAD

**Issue by Bilge** [jumbojett/OpenID-Connect-PHP#265]
In the current release, and on `master`, `composer.json` specifies the dependency on `paragonie/random_compat` twice, with two different version constraints. 

https://github.com/jumbojett/OpenID-Connect-PHP/blob/4f95102af87f86c43e8191ec6e90d9f35ed1ce5f/composer.json#L8-L11

I believe this is invalid.

**Comment by JuliusPC** [comment]
See PR #239.

**Comment by DeepDiver1975** [comment]
Fied
