### ISSUE TITLE
Configurable URI Well-known

### ISSUE THREAD

**Issue by QB-Git** [jumbojett/OpenID-Connect-PHP#281]
Hi,

I am using an openid project with a well-known URI not of the form https://URL/.well-known/openid-configuration

I saw in the source code that "/.well-known/openid-configuration" was written in raw. Is there a way to override this parameter? Would this require a pull request?

For now an alternative solution is to declare all my endpoints, but it's quite heavy.

I was thinking of proposing something like this if no solution exists yet :
```php
private function getWellKnownConfigValue($param, $default = null) {
  // If the configuration value is not available, attempt to fetch it from a well known config endpoint
  // This is also known as auto "discovery"
  if(!$this->wellKnown) {
      // $well_known_config_url = rtrim($this->getProviderURL(), '/') . '/.well-known/openid-configuration';
      $well_known_config_url = rtrim($this->getProviderURL(), '/') . $this->wellKnownConfigUrlBase;
      if (count($this->wellKnownConfigParameters) > 0){
          $well_known_config_url .= '?' .  http_build_query($this->wellKnownConfigParameters) ;
      }
      $this->wellKnown = json_decode($this->fetchURL($well_known_config_url));
  }
  // ...
}
```
With of course the addition of the variable `wellKnownConfigUrlBase` in the class.

Did someone have the same issue or have a solution for that ?

Thank you.

**Comment by DeepDiver1975** [comment]
How does the URI look like in your case? THX

**Comment by QB-Git** [comment]
My URI looks like this : https://URL/metadata/oidc-profile-full
I do not have the hand in the form of this URI.

**Comment by DeepDiver1975** [comment]
But this URL does not follow the specification of openid service discovery.
I think it would be best to change your IDP to follow the specs.

**Comment by QB-Git** [comment]
I understand, but if I have to keep this URI, is there any other solution?

**Comment by DeepDiver1975** [comment]
Depending on the tech stack which you use to implement your idp you can define http rewrite rules.

**Comment by QB-Git** [comment]
Thanks for your answer, I will try that !
