### ISSUE TITLE
How to get multiple UserInfos using requestUserInfo($attribute)?

### ISSUE THREAD

**Issue by q2apro** [jumbojett/OpenID-Connect-PHP#301]
Currently I am fetching the data like:

```
$userdata = array(
	'uuid' => $oidc->requestUserInfo('uuid'),
	'realuser' => $oidc->requestUserInfo('realuser'),
	'givenname' => $oidc->requestUserInfo('given_name'),
	'email' => $oidc->requestUserInfo('email'),
);
```

However, each creates a separate request to the server.

How can I ask for several userinfos?

Something like:

      $userdata = $oidc->requestUserInfo('uuid', 'realuser', 'gevenname', 'email'),  // ?

Here someone was creating a commit with an array: https://github.com/jumbojett/OpenID-Connect-PHP/pull/52/commits/452a85bbf9e02265b9928c36b767915635672da6

However, the recent code looks different: https://github.com/jumbojett/OpenID-Connect-PHP/blob/4ac6b24ad4a011017ebea0fbad6aa5be4457cc9a/src/OpenIDConnectClient.php#L1150

**Comment by DeepDiver1975** [comment]
call the method with null and you get the array with all propy

**Comment by q2apro** [comment]
`$userdata = $oidc->requestUserInfo(null);` works 👍 

Thank you.
