### ISSUE TITLE
missing required parameter(s) (client_id)

### ISSUE THREAD

**Issue by alandra25** [jumbojett/OpenID-Connect-PHP#310]
Hi, i'm testing your function like in Example 5 Request Resource Owners Token (with client auth).
I already set all requirement but have this return error :

{
    "error": "invalid_request",
    "error_description": "missing required parameter(s) (client_id)"
}

Is there any way you can look at this error ?

**Comment by DeepDiver1975** [comment]
This error is returned from your IdP.

As it states the client_id is expected.

client id is the second ctor argument

```
$oidc = new OpenIDConnectClient('https://id.provider.com',
                                'ClientIDHere',
                                'ClientSecretHere');

**Comment by alandra25** [comment]
Hi @DeepDiver1975, i already set all the requirement and still get that error, including ClientID, ClientSecret, and provider URL

**Comment by DeepDiver1975** [comment]
What is our IdP?
