### ISSUE TITLE
Intermittent session issues

### ISSUE THREAD

**Issue by diggersworld** [jumbojett/OpenID-Connect-PHP#320]
Hi, 

I've been experiencing intermittent issues when using this package in which authorization requests fail validation of the `state` and `nonce` parameters because they don't exist in the session. What typically happens is the following:

1. initial authorization request is constructed and attempts to record nonce and state values to the session, the user is then redirected to the auth provider.
2. on return from auth provider the session is started but the nonce and state values are not present and therefore when validating those values match the response payload, an exception is thrown.
3. attempting to log in again, step 1 is repeated.
4. on return from auth provider the session is started only this time the nonce and state values are present and pass the validation.

Has anyone else experienced this, and if so, did you manage to resolve it?

**Comment by ricklambrechts** [comment]
Do you use this package in a framework like Laravel?
How does the setup look like, is the application on multiple servers behind a load balancer?

For Laravel and HA support I extended the OpenIDConnectClient and override the session functions to use Laravel's session functions.

**Comment by DeepDiver1975** [comment]
Possible solution is to review the same site cookie settings.
Depending on the used php version different default values are used which can have massive impact on the functionality of openidconnect.

refs https://auth0.com/blog/browser-behavior-changes-what-developers-need-to-know/#What-Might-Be-Affected-
