### ISSUE TITLE
phpseclib now natively supports json webkeys

### ISSUE THREAD

**Issue by mrvanes** [jumbojett/OpenID-Connect-PHP#321]
https://github.com/jumbojett/OpenID-Connect-PHP/blob/96b1295daa137ab2f9f1ebee50278e79ba280ad8/src/OpenIDConnectClient.php#L975

OpenID-Connect-PHP can now do without the xml wrapping of keys and natively parse the json webkeys in phpseclib:
https://github.com/phpseclib/phpseclib/releases/tag/3.0.15
https://github.com/phpseclib/phpseclib/commit/0b3c6e27fcdd58d747cea054d536e319a38ca5be

**Comment by DeepDiver1975** [comment]
taken care of in #327
