### ISSUE TITLE
since v0.9.9 The provider client_assertion_type could not be fetched

### ISSUE THREAD

**Issue by azurams** [jumbojett/OpenID-Connect-PHP#329]
Hi, I'm using Keycloak with basic "Client ID / Secret" client auth. 

Authentication used to work prior to v0.9.9.
Since 0.9.9, I got the following error :  "The provider client_assertion_type could not be fetched"

It seems that, since "client_secret_jwt" is in supported token endpoint auth methods, OpenIDConnectClient tries to use this method.
And Keycloak may be not well configured since  "client_assertion_type" et "client_assertion"  is missing from the `.well-known/openid-configuration`

How can I force OpenIDConnectClient to use `client_secret_basic` instead of `client_secret_jwt` ?

**Comment by DeepDiver1975** [comment]
I can only think of adding some config option to explicitly enable client_secret_jwt to make sure we don't have such a breaking behavior.

Gimme a moment to come up with a PR.

**Comment by azurams** [comment]
thank you for your quick reply.
I gave your PR a try, and it works as expected and fix my issue.

**Comment by DeepDiver1975** [comment]
@azurams here is an alternative approach - should give the same behavior - maybe you still want to give this one a try
https://github.com/jumbojett/OpenID-Connect-PHP/pull/331

Thanks a lot!

**Comment by azurams** [comment]
@DeepDiver1975 the solution you merged in the new release 0.9.10 fully fits my needs.
 Thanks a lot !
