### ISSUE TITLE
PKCE code verifier not specified

### ISSUE THREAD

**Issue by divyeshamreliya** [jumbojett/OpenID-Connect-PHP#339]
Hello
I am getting below issue in callback method, I am successfully login into third party open id but after that I am getting below error

Fatal error:  Uncaught Jumbojett\OpenIDConnectClientException: PKCE code verifier not specified

![image](https://user-images.githubusercontent.com/112490437/195548384-f2481033-24be-4595-b43e-9ba227ba353d.png)

**Comment by ricklambrechts** [comment]
Did you set a code challenge method?
https://github.com/jumbojett/OpenID-Connect-PHP#example-8-pkce-client

**Comment by divyeshamreliya** [comment]
@ricklambrechts 
Thanks :) After setting code challenge method, issue resolved.
