### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by herchila** [jumbojett/OpenID-Connect-PHP#34]
Hi, 
I recently try to test it but...

```
Notice: Trying to get property of non-object in OpenIDConnectClient.php5 on line 268

# Line 268
$value = json_decode($this->fetchURL($well_known_config_url))->{$param};
```

Any clue?

Thanks!

**Comment by jumbojett** [comment]
@herchila - First thought:  Verify that your provider has a well known configuration available.
In other words see if the following endpoint exists: `https://provider.url.com/.well-known/openid-configuration`

If it doesn't you'll have to manually set your provider's details with the class methods.

**Comment by blafasel42** [comment]
i have a similar issue:
PHP Notice:  Trying to get property of non-object in .../OpenIDConnectClient.php on line 290
PHP Fatal error:  Uncaught OpenIDConnectClientException: The provider authorization_endpoint has not been set. Make sure your provider has a well known configuration available. in .../OpenIDConnectClient.php:295

the exception is cool now, points to the right problem. but is it possible to mute the notice before?

**Comment by jumbojett** [comment]
@blafasel42 sure thing!
```
// Report simple running errors
error_reporting(E_ERROR | E_WARNING | E_PARSE);
```
