### ISSUE TITLE
Problems using this package in a system with Azure AD

### ISSUE THREAD

**Issue by tomasdelvechio** [jumbojett/OpenID-Connect-PHP#351]
Hello, thanks for this lib.

I'm a web dev without many experience on SSO and OIDC. I don't get how to work with OIDC and AzureAD.

I need to build a complete "workflow" for users using a test app in AzureAD and my PHP system. There is: login, logout, get email or userid (sub).

I build this script (ommit values specific of my app): https://gist.github.com/tomasdelvechio/5fa4d25cb7399eba21e33370f790a2d1#file-testing-php

The above script redirect to AzureAD, let me login in success and return an id_token, state and session_state. But from this, I can't get the sub value, email, etc...

From the AzureAD app I check the options redirect uri and ID tokens (used for implicit and hybrid flows). 

Questions:

 - I have to call `authenticate()` method in each request to my app? or is it enough with just create Oidc object?
 - Some software (open source) implement full the AzureAD API in php using this lib, to learn from there how to use the package for my app?
 - Some reference code or other material relevant? I read RFCs, OIDC doc online, this repo Wiki, issues, PRs, etc...

**Comment by Didji** [comment]
Hi, I think I ran into the same issue recently, and I fixed it by adding the `token` response type to the client.
Line 40 of your script : `$oidc->setResponseTypes(array('id_token', 'token'));`

With that, the authenticate endpoint will return you both an ID token and an access token that will be used after in the userinfo endpoint

Also, you should check the access token option in Azure AD.

**Comment by tomasdelvechio** [comment]
I didn't use this lib anymore, we use other approach to the solution

Thanks
