### ISSUE TITLE
Authenticate Problem on php 8

### ISSUE THREAD

**Issue by kastoras** [jumbojett/OpenID-Connect-PHP#353]
If you use this library on a php 8 project with php warnings enabled you experience this problem. 

In OpenIDConnectClient class, in authenticate method there will be a warning in line 341 $_REQUEST['state'] that the state in not defined.
And after this error you get this error Warning: Cannot modify header information - headers already sent by... and then it fails.

I will provide a pull request, with an extra check if $_REQUEST['state'] exists.

**Comment by kastoras** [comment]
A pull request for this one:
https://github.com/jumbojett/OpenID-Connect-PHP/pull/354

**Comment by LauJosefsen** [comment]
By doing

```php
if (isset($_REQUEST['state']) && ($_REQUEST['state'] !== $this->getState())) {
```

Don't you bypass the state check if the state is not set? I assume you want something like

```
if (!isset($_REQUEST['state']) || ($_REQUEST['state'] !== $this->getState())) {
```

As you are then throwing the exception if the state is not set, instead of bypassing it.

**Comment by nikolaosanthimidis** [comment]
Hi @LauJosefsen, you are correct. I changed my code.
Thanks.

**Comment by kastoras** [comment]
Hi @LauJosefsen, you are correct. I changed my code.
Thanks.
