### ISSUE TITLE
Keycloak

### ISSUE THREAD

**Issue by anhaabaete** [jumbojett/OpenID-Connect-PHP#355]
hi! Happy new year folks!
Someone already used OCPHP on Keycloak?

**Comment by DeepDiver1975** [comment]
> OCPHP

what is that? **O**penid-**C**onnect-**PHP**?

Short answer: yes it has been done multiple times.
Long answer: you need to dig yourself into keycloak, it's configuration and implement the client side with this lib accordingly. Using the given examples this should be pretty straight forward.
