### ISSUE TITLE
Data cannot be retrieved. The field is too big

### ISSUE THREAD

**Issue by alenadierickx** [jumbojett/OpenID-Connect-PHP#356]
**Hello. I useOpenID-Connect-PHP  to get data from a remote server. The problem is that the role field is too large and I can't get the data. Osprey is not available to me.  For example:**

  "roles": [
    "External Users",
    "Function SM2 : DIG",
    "Site-XXXXXXX-0003646",
    "Site-XXXXXXX-0005818",
    "Site-XXXXXXX-0005834",
    "Site-XXXXXXX-0006554",
    "Site-XXXXXXX-0006227",
    "Site-XXXXXXX-0006280",
    "Site-XXXXXXX-0006689",
    "Site-XXXXXXX-0006849",
    "Site-XXXXXXX-0007004",
    "Is MIA User",
    "Is User XXXXXXX",
    "Is Metreur",
    "Is SM2 User",
    "Is User XXXXXXX",
    "Site-XXXXXXX-0007037"
  ],
  
 **If I reduce the amount of incoming data it works. For example:**
 
  "roles": [
    "External Users",
    "Function SM2 : DIG",
    "Site-XXXXXXX-0006280",
    "Site-XXXXXXX-0006689",
    "Site-XXXXXXX-0006849",
    "Site-XXXXXXX-0007004",
    "Is MIA User",
    "Is User XXXXXXX",
    "Is Metreur",
    "Is SM2 User",
    "Is User XXXXXXX",
    "Site-XXXXXXX-0007037"
  ],
  
  **If there is a way to solve this problem? 
  
  Thank you in advance for your help.**

**Comment by ricklambrechts** [comment]
Could you be more explicit on what the problem is?

Is this the output of `$oidc->requestUserInfo();`?

**Comment by alenadierickx** [comment]
> Could you be more explicit on what the problem is?
> 
> Is this the output of `$oidc->requestUserInfo();`?

Yes. Is this the output of $oidc->requestUserInfo();

**Comment by DeepDiver1975** [comment]
What is the explicit error/exception you are receiving?

**Comment by alenadierickx** [comment]
> What is the explicit error/exception you are receiving?

I don't are receiving error/exception. I get all information except the 'roles'. Here is an example :

object(stdClass)#35 (13) {
  ["country"]=>
  string(6) "France"
  ["sub"]=>
  string(15) "nicolas.brunaud"
  ["login_user_name"]=>
  string(15) "nicolas.brunaud"
  ["principal_domain"]=>
  string(7) "Default"
  ["preferred_username"]=>
  string(15) "nicolas.brunaud"
  ["given_name"]=>
  string(7) "Nicolas"
  ["locale"]=>
  string(5) "fr-FR"
  ["country_code"]=>
  string(2) "FR"
  ["schmidt-site"]=>
  array(10) {
    [0]=>
    string(7) "0003646"
    [1]=>
    string(7) "0005818"
    [2]=>
    string(7) "0005834"
    [3]=>
    string(7) "0006554"
    [4]=>
    string(7) "0006227"
    [5]=>
    string(7) "0006280"
    [6]=>
    string(7) "0006689"
    [7]=>
    string(7) "0006849"
    [8]=>
    string(7) "0007004"
    [9]=>
    string(7) "0007037"
  }
  ["displayname"]=>
  string(15) "Nicolas BRUNAUD"
  ["name"]=>
  string(56) "BRUNAUD Nicolas - SM2Id-5254 - SM2-CollaborateurId-12796"
  ["family_name"]=>
  string(7) "BRUNAUD"
}

**Comment by DeepDiver1975** [comment]
Looks like a missing scope then.....

**Comment by DeepDiver1975** [comment]
Please check on network level what is returned from your IDP.
Either the roles field is in the json or it is not.
There are no limitations within the code of this library.
