### ISSUE TITLE
Custom param

### ISSUE THREAD

**Issue by phpSimplex** [jumbojett/OpenID-Connect-PHP#367]
Is there a possibility to add a custom param that will be send back when redirecting?
I tried in `setRedirectUrl("url/.com/login?customCode=XXX")` but that didnt work and got me the error 'Invalid Redirect Uri'

**Comment by phpSimplex** [comment]
Well the problem is that the session changes when the redirect happen so i have a different session_id.
The idea was to send the session_id within the redirect uri to reset the session with the old id

**Comment by DeepDiver1975** [comment]
if the session id changes this reads more like an issue in your same site cookie setup - refs https://web.dev/samesite-cookies-explained/
