### ISSUE TITLE
Intermittent invalid_grant when calling $oidc->authenticate()

### ISSUE THREAD

**Issue by blasto333** [jumbojett/OpenID-Connect-PHP#368]
We have noticed that we get intermittent exception for invalid Grant when being redirected after sign in. Our workaround us to have the user try again which works.

This error is happening after the user signs in and redirected back.

have you run into this issue before is it an error with the authentication server?

**Comment by DeepDiver1975** [comment]
Hard to tell without any further details. What exception do do see? Which IdP are you talking to?

**Comment by blasto333** [comment]
@DeepDiver1975 Pretty sure I figured it out on my end. I was doing multiple redirects which caused duplicate requests to IDP
