### ISSUE TITLE
UserInfo endpoint MUST support Bearer Token Usage

### ISSUE THREAD

**Issue by juanifioren** [jumbojett/OpenID-Connect-PHP#38]
Hi,
UserInfo endpoint should have support for [Bearer Token Usage](http://tools.ietf.org/html/rfc6750). Am using [this framework](https://github.com/juanifioren/django-oidc-provider) as the provider. See how expect request:

```
POST /openid/userinfo/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer [ACCESS_TOKEN]
```

This package use query string for access token.

```
"GET /openid/userinfo/?schema=openid&access_token=9a01043111f84e18a8ef392771592a59 HTTP/1.1" 401 0
```
#### The Spec say:

> The Access Token obtained from an OpenID Connect Authentication Request MUST be sent as a Bearer Token. It is RECOMMENDED that the request use the HTTP GET method and the Access Token be sent using the Authorization header field. http://openid.net/specs/openid-connect-core-1_0.html#UserInfoRequest

Greetings!

**Comment by jricher** [comment]
We solved this in our Java client by having a configuration switch to select the token presentation method:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/commit/325a200f167f373b147ad0dbdb7673379d434475

**Comment by juanifioren** [comment]
Yup, nice @jricher. I'll have to add Query support also haha.

**Comment by svrooij** [comment]
This issue was fixed a long time ago, by [this commit](https://github.com/jumbojett/OpenID-Connect-PHP/commit/efff1b70e83545ffdb79b3109f3092b698261585).
Can this be closed?

**Comment by jumbojett** [comment]
Yep @svrooij ! Thanks!
