### ISSUE TITLE
Issue when running composer require jumbojett/openid-connect-php

### ISSUE THREAD

**Issue by meeshellmartini** [jumbojett/OpenID-Connect-PHP#390]
Hi, I'm new to OpenID and I'm tring to install OpenID Connect. I received the following error message. 

Error message:
In JsonFile.php line 347:

  "./composer.json" does not contain valid JSON
  Parse error on line 1:

  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['  

When I open my composer.json file, I see the following three lines and nothing else.

{
    "require": {
        "jumbojett/openid-connect-php": "^0.9.10"

**Comment by DeepDiver1975** [comment]
Please learn how to use composer - https://getcomposer.org/doc/01-basic-usage.md
