### ISSUE TITLE
No license information

### ISSUE THREAD

**Issue by guss77** [jumbojett/OpenID-Connect-PHP#40]
Hi, this library is missing a license specification. 

I want to fork it to make it a bit more complicated for my specific need, but without an Open Source license I can't really do it.

Can you please specify what license this library is distributed under? I'd appreciate it if in can be a BSD or MIT license, but I can work with most OSI approved licenses, if you rather use something else.

**Comment by jricher** [comment]
I'd recommend the Apache license for this project. In my experience it has the best balance of rights and protections. 

@guss77 Thank you for being mindful of the licensing terms! Many developers aren't and it's great to see that.
