### ISSUE TITLE
Cant get codeVerifier in redirectUri if we make authorization flow using PKCE

### ISSUE THREAD

**Issue by salmanx** [jumbojett/OpenID-Connect-PHP#400]
For PKCE support we add `setCodeChallengeMethod` when we initialize the `OpenIDConnectClient`. It redirect us to our OIDC server with a code challenge, after doing authentication, we are redirected to our reidirectUrl where we need to make a request to token_endpoint to receive the access_token. To make a post request to token_endpoint, we need to  pass the code that we receive in our redirectUri. It also mandatory to pass the codeVerifier along with the code, client id and secret. But in this step we dont have any codeVerifier. Package itself store the codeVerifier in session but if read it from session, it always return null.

**Comment by DeepDiver1975** [comment]
Please review your cookie same site setup - it has to be lax or none. Strict does not work.
see https://php.watch/articles/PHP-Samesite-cookies
