### ISSUE TITLE
SERVER_PORT always causes port in redirect URL

### ISSUE THREAD

**Issue by timsmid** [jumbojett/OpenID-Connect-PHP#403]
When `$_SERVER['SERVER_PORT']` is set, the `getRedirectUrl` method always includes a port number, even when the port is 80 or 443. This is caused by comparing a string (`$_SERVER['SERVER_PORT']`) with an integer (`80` and `443`).

I will submit a PR to resolve this issue.

**Comment by jasongill** [comment]
@timsmid thank you for this, after upgrading to 1.0.0 we couldn't log in with Okta due to redirect URI mismatch so adding :443 to the allowed URL's in Okta allowed us to work around this bug until your PR is merged.

**Comment by NicoHaase** [comment]
Any news on this topic? We're facing this bug as well

**Comment by azurams** [comment]
thank you @timsmid !

**Comment by DeepDiver1975** [comment]
PR merged -> close

**Comment by q2apro** [comment]
⚠️ Note that now having always `:443` inside the `redirect_uri` breaks a lot of SSO sites, that have whitelisted in their firewall e.g. `mydomain.com/*` but not `mydomain.com:443/*`.

Is there any option to prevent this behavior?

**Comment by timsmid** [comment]
That is exactly the problem that this issue (and PR) solve. The port will be dropped from the redirect URL if it is 443 or 80. See https://github.com/timsmid/OpenID-Connect-PHP/blob/470895e/src/OpenIDConnectClient.php#L716:

```
$port = (443 === $port) || (80 === $port) ? '' : ':' . $port;
```

Previously, `$port` contained 443 as a string, which caused the port to be incorrectly included in the redirect URL. With the latest version of this library, the redirect URL should not contain `:443`.

**Comment by q2apro** [comment]
Strange, in my case the `:443` is always added, even with this exact code.
