### ISSUE TITLE
Redirect doesn't remove state, session_state, and code params

### ISSUE THREAD

**Issue by db79db** [jumbojett/OpenID-Connect-PHP#408]
I feel I'm missing something, but when I run the client_example.php (using Keycloak 22.0.4 as my OIDC server) it always returns with the state, session_state, and code GET variables in the URL after authenticate() is called. From what I can tell these _should_ get removed as part of the authenticate() procedure, however it's not in my case (even if I have used setRedirectURL()).

**Comment by ricklambrechts** [comment]
The query parameters are not magically removed. In the most user flows, after redirected to the application with the query parameters, this package does multiple checks and your application can get the user info. After that, you normally put the needed information in your session / do your logic and redirect the user to a page in the application.

**Comment by db79db** [comment]
Ah that makes sense, thank you!
