### ISSUE TITLE
Support dropped for phpseclib 2.*?

### ISSUE THREAD

**Issue by slaweknaczynski** [jumbojett/OpenID-Connect-PHP#409]
It would probably be a good idea to mention in changelog that support for phpseclib v2 was dropped. This is a significant change and no mention of it anywhere. Any reason why the support was dropped? thanks

**Comment by ricklambrechts** [comment]
Thats why its a major update. But indeed it should have been a seperate line in the changelog.
It was part of the `PHP 7.0 is required`. https://github.com/jumbojett/OpenID-Connect-PHP/pull/327

**Comment by DeepDiver1975** [comment]
Generally speaking such information is in the composer file and composer will grab the correct version or report back a version compatibility issue.

From my pov this is by far superior compared to a changelog entry.

Never the less: feel free to submit a pull request to change the change log.
