### ISSUE TITLE
Debug Mode ?

### ISSUE THREAD

**Issue by Tchiboun** [jumbojett/OpenID-Connect-PHP#418]
Hello, 

Have you develop a debug mode ? 
I don't know why requestUserInfo() return a NULL value. My parameters for the OpenIDConnectClient object is correct.

Thanks for your answer.

**Comment by DeepDiver1975** [comment]
Maybe your idp does not support the user info endpoint?
I would suggest to use xdebug for PHP debugging and some ide to debug.
