### ISSUE TITLE
Should the timestamps in the claims be validated?

### ISSUE THREAD

**Issue by Spitzbub** [jumbojett/OpenID-Connect-PHP#43]
Looks like the code covers the first couple of the items in the list at http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation, but not the others, for example, expiration time. Is this intentional?

**Comment by jumbojett** [comment]
@Spitzbub It was not intentional. 
@jricher do you have any input?

**Comment by radenui** [comment]
I believe this is addressed by #61
`exp` claim is validated along with non standard `nbf` (not before) claim

**Comment by jumbojett** [comment]
Closing based on recent PR.
