### ISSUE TITLE
Curl error: (35) OpenSSL/3.0.13: error:0A00010B:SSL

### ISSUE THREAD

**Issue by atilling** [jumbojett/OpenID-Connect-PHP#434]
Installed the latest version with composer on a fresh ubuntu server. PHP 8.3.6 with CURL and JSON. Self signed cert but using the settings:

$oidc->setVerifyHost(false);
$oidc->setVerifyPeer(false);

PHP Fatal error:  Uncaught Jumbojett\\OpenIDConnectClientException: Curl error: (35) OpenSSL/3.0.13: error:0A00010B:SSL routines::wrong version number in /var/www/html/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php:1435
Stack trace:
#0 /var/www/html/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(619): Jumbojett\\OpenIDConnectClient->fetchURL()
#1 /var/www/html/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(594): Jumbojett\\OpenIDConnectClient->getWellKnownConfigValue()
#2 /var/www/html/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(1586): Jumbojett\\OpenIDConnectClient->getProviderConfigValue()
#3 /var/www/html/index.php(12): Jumbojett\\OpenIDConnectClient->register()
#4 {main}\n  thrown in /var/www/html/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php on line 1435

**Comment by DeepDiver1975** [comment]
unrelated to this library. your self signed cert is not understood by openssl

**Comment by atilling** [comment]
The self signed cert was generated by openssl. I thought the verifyhost and verifypeer settings where there to ignore the SSL issues?
