### ISSUE TITLE
A trouble setting up the OpenIDConnectClient.php

### ISSUE THREAD

**Issue by abdulart** [jumbojett/OpenID-Connect-PHP#45]
Hello. I apologise for my weak skills, but this kind of code really tough, that is why I would like to ensure right set up of this client.

So, I installed package OpenID-Connect-PHP-master , that includes (README.md, OpenIDConnectClient.php, LICENSE.txt,  composer.json, client_example.php). 
Client_example.php includes the following code:

`<?php

require "../../autoload.php";   # ** # <--- I dont actually understand which document should i past here**

$oidc = new OpenIDConnectClient('http://myproviderURL.com/',
                                'ClientIDHere',
                                'ClientSecretHere');

$oidc->authenticate();
$name = $oidc->requestUserInfo('given_name');

?>`

So it would be very helpful if someone provides a short guide how should I exactly install this package.

Thank you.

**Comment by rasodu** [comment]
Hi abdulart,
This library can now be installed using composer. Additional instructions for installation are added to readme file. 'autoload.php' file created by composer to handle autoloading of all packages installed using composer. Let me know if you still have trouble installing.

**Comment by gnm67** [comment]
Hi, i'm on windows 'composer' doesn't work.

**Comment by abdulart** [comment]
rasody, thank you for answer. But I still do not understand what actually means installing this package. 

I do need on my website to have an abstract button, when you push it this OpenId client gets users data and sends it back to my database.

Which code from archive I downloaded should I insert on my site? Where should I get file autoload.php 
And where to get a composer?

Thank you.

**Comment by rasodu** [comment]
You can read section 2(linux, unix or osx) or section 3(windows) at https://getcomposer.org/doc/00-intro.md for steps on installing composer.

Once you run composer command to install package, it will create 'vendor/' folder in the directory where you ran the command. This folder will contain an 'autoload.php' file(vendor/autoload.php) and some other folders.

Only file you will need after installing package using composer is something similar to 'client_example.php' that will pull user data and insert it into database . You need to replace 'require "../../autoload.php";' with 'require "&lt;location-of-composer-package-install-folder-path>/vendor/autoload.php"'.

**Comment by abdulart** [comment]
rasodu. Thank you for your answers, 

I did installed composer, and now the only thing i missed is how to create the command for composer to install the package

Thank you.

**Comment by jumbojett** [comment]
@abdulart `composer require jumbojett/openid-connect-php` 
Closing this PR. Feel free to re-open if you're still having issues.
