### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Hornwitser** [jumbojett/OpenID-Connect-PHP#54]
I want to authenticate users with OpenID in my application, and this library describing its goal of

> [hoping] to encourage OpenID Connect use by making it simple enough for a developer with little knowledge of the OpenID Connect protocol to setup authentication

makes this a perfect choice as I've never dealt with OpenID before, and I just want it to work (tm).  But I can't wrap my head around any of this.  Am I supposed to read the OpenID specification and the source code of this library to understand how to use this?  I thought that was what this library was supposed to relieve me from!

The grand total of documentation on how to use this that I've found so far is 3 short examples with no description at all on what the examples do or how they work, and a very, very brief description of each of the API entry points.  That makes this project to me almost unusable, the barrier to entry is pretty much the same as any of the other more heavy and feature laden libraries.  If this project is to be of any use for casual developers it **has to have** documentation that adequately describes the processes involved with authenticating a user, and how this library accomplishes it.

**Comment by jricher** [comment]
Thank you for pointing that out, and we look forward to your pull request providing documentation to your standards.

**Comment by Hornwitser** [comment]
As much as I would like to, I do not have the time nor the resources to properly familiarize myself with the 80k words of specifications that compromises the basics of OpenID Connect operation.  It was my expectation that this library would let me avoid that.  Because of this, I will be unable to provide the level of quality and correctness to such a documentation that I would deem adequate.

In other words: I'll write something when I get it to work (from no less than trail an error).
