### ISSUE TITLE
typo line 421

### ISSUE THREAD

**Issue by Tormalik** [jumbojett/OpenID-Connect-PHP#56]
`421:         if (sizeof($this->setResponseTypes) > 0) {`
should be
`421:         if (sizeof($this->responseTypes) > 0) {`

**Comment by corentingi** [comment]
I made a PR that solves this #55 
This currently waiting for approval, for now you can point your composer to my repository if you will.
https://github.com/corentingi/OpenID-Connect-PHP

Enjoy ;)

**Comment by jumbojett** [comment]
Merged - Thanks @corentingi
