### ISSUE TITLE
Repeated port in redirectURL parameter when running under IIS

### ISSUE THREAD

**Issue by mrmorcs** [jumbojett/OpenID-Connect-PHP#58]
I'm running a test client under IIS at https://localhost:44396/.

When the code redirects to the identity provider - it is adding the port number twice in the redirectURL (i.e. https://localhost:44396:44396/)

I've tracked this down to the use of _SERVER["HTTP_HOST"], which in my case includes the port.

I've modified the code to strip the port if present. I'll try and send a pull request with this fix in.

**Comment by bigjumpjames** [comment]
N.b. Apparently this value is the raw host header sent by the browser, so it's probably more to do with what browser I was using rather than IIS.

**Comment by genebean** [comment]
I am running into this same issue when testing under vagrant...

**Comment by mrmorcs** [comment]
@genebean now fixed https://github.com/jumbojett/OpenID-Connect-PHP/pull/59

@jumbojett should I close this issue now? :)

**Comment by jumbojett** [comment]
Closed! Thanks @mrmorcs 👍

**Comment by genebean** [comment]
👍 Thanks! I'll get back to playing soon now that this is resolved :-)
