### ISSUE TITLE
PHP incompatibility

### ISSUE THREAD

**Issue by rask** [jumbojett/OpenID-Connect-PHP#64]
The package has a PHP version requirement of `>=5.2`, but the code contains 5.2 incompatible code, e.g. short array declarations. Example in https://github.com/jumbojett/OpenID-Connect-PHP/blob/master/OpenIDConnectClient.php#L470

**Comment by jumbojett** [comment]
Thanks @rask ! 👍 I just bumped the requirement. Feel free to submit a PR in the future.
