### ISSUE TITLE
OpenIDConnectClientException: Cannot supply client credentials in both the Authentication header and the request-body

### ISSUE THREAD

**Issue by rajnisheu** [jumbojett/OpenID-Connect-PHP#75]
Hi, I am using okat to test from my localhost xampp install on windows. First I got an error regarding phseclib which I had to include. This is my code with cert turned off for now:

````
include('phpseclib1.0.5/Crypt/RSA.php');
require "OpenIDConnectClient.php";

$oidc = new OpenIDConnectClient('https://myaccount.oktapreview.com',
                                'id',
                                'secret');
$oidc->setVerifyHost(false);
$oidc->setVerifyPeer(false);
$oidc->authenticate();
$name = $oidc->requestUserInfo('given_name');
````

Am redirected to okat and able to pass my creds. Also getting correctly redirected to local file after entering creds on okat. On callback to local am getting the following error:
OpenIDConnectClientException: Cannot supply client credentials in both the Authentication header and the request-body. in C:\xampp\htdocs\openid\OpenIDConnectClient.php on line 228

Not able to figure out if this is an okat issue or openid-connect-php issue.
Any help appreciated.

**Comment by jumbojett** [comment]
Hi @rajnisheu ! My thoughts are as follows. 

1. It appears that you're not using composer to install the library. (Thus the missing libs error.)
2. `id` and `secret` are place holders for actual value that need to be obtained from your provider. Are you using actual values in this place?

Closing the issue for now. Feel free to re-open if you have additional questions!

**Comment by rajnisheu** [comment]
I can't find how to re-open this for topic no 2.
There's an issue when un-setting array fields in case of `client_secret_basic` which is fixed by also un-setting `client_id` as follows:
````
# Consider Basic authentication if provider config is set this way
 if (in_array('client_secret_basic', $token_endpoint_auth_methods_supported)) {
   $headers = ['Authorization: Basic ' . base64_encode($this->clientID . ':' . $this->clientSecret)];
   unset($token_params['client_id']); // unset client_id as well
   unset($token_params['client_secret']);
 }
````
Could be Okta specific. Will run tests with other providers.
