### ISSUE TITLE
Unncessary getProviderConfigValue("token_endpoint_auth_methods_supported") call?

### ISSUE THREAD

**Issue by asmarius** [jumbojett/OpenID-Connect-PHP#77]
I'm wondering about why there is an unused variable in line 481 https://github.com/jumbojett/OpenID-Connect-PHP/blob/master/OpenIDConnectClient.php#L481 of OpenIDConnectClient.php

`        $token_endpoint_auth_methods_supported = $this->getProviderConfigValue("token_endpoint_auth_methods_supported");
`

Is it by intention to throw an error if there is no "token_endpoint_auth_methods_supported" config set?

**Comment by jumbojett** [comment]
Good question @asmarius. The variable is definitely not needed. (I think it was a copy from line 509.) I'd like you to get credit for contributing to our project. Would you mind submitting a pull request for this change?
