### ISSUE TITLE
phpseclib version

### ISSUE THREAD

**Issue by msantic** [jumbojett/OpenID-Connect-PHP#78]
I'm getting PHP Fatal error:  Undefined class constant 'PUBLIC_FORMAT_XML'. I see in the code you are using Crypt_RSA::PUBLIC_FORMAT_XML syntax while latest version from http://phpseclib.sourceforge.net doesn't have class constant. Am I missing something obvious?

**Comment by jumbojett** [comment]
@msantic thanks for reporting this. 

1. Did you install our lib using composer? (It calls for a specific version of phpseclib.)
2. Which version of PHP are you using?

**Comment by msantic** [comment]
1. No, I just pulled from GitHub. Just tried with composer install and it works as expected now. Thank you
2. php -v
     PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58)
