### ISSUE TITLE
Relicensing possible?

### ISSUE THREAD

**Issue by max-wittig** [jumbojett/OpenID-Connect-PHP#87]
I would like to use your library for the [Fossology project](https://github.com/fossology/fossology). 
Because your project is licensed under the Apache-2.0 License it would be unfortunately not possible to integrate it, as the Apache-2.0 License is not compatible with the GPL-2.0 License. Would you mind changing the license or to add dual-licensing to your library to be compatible with Fossology? (e.g. using MIT, BSD, GPL-2.0 License)

Thanks for your consideration

**Comment by jumbojett** [comment]
@max-wittig we'd be willing to work with you. 
@jricher guidance?

**Comment by jumbojett** [comment]
@max-wittig please send an email to poornima@mitre.org and reference this discussion.
