### ISSUE TITLE
Unable to login user to Mediawiki using inhouse identity server.

### ISSUE THREAD

**Issue by info-kishorkunal** [jumbojett/OpenID-Connect-PHP#97]
**Getting below error:**

> OpenIDConnectClientException: Unable to verify JWT claims in C:\xampp\htdocs\mywiki\extensions\OpenIDConnect\vendor\jumbojett\openid-connect-php\OpenIDConnectClient.php:228

**URL is -**

http://localhost/mywiki/index.php/Special:PluggableAuthLogin?code=91b01f5527c63868d1f8383c9dd4b9f5a2a4e873493c5761fcf1c77cd7feefa2&scope=openid%20email&state=81ec95aaffb00ffe7132e9738e908cac&session_state=BMo3BqCddmkNYzXleTM4p1LdoRQb7FLn9TfK5hygKjQ.2099bc7dbd791f3c98ae22216db8d02d

**configuration in local setting**

> wfLoadExtension( 'OpenIDConnect' );
> 
> $wgOpenIDConnect_Config['http://localhost:5000'] = [
>     'clientID' => 'wiki',
>     'clientsecret' => 'wikisecret',
> 	'scope' => array( 'openid',  'email')
> ];

**Comment by jumbojett** [comment]
@info-kishorkunal This is not an issue with the lib. This message simply means security may be in question. Something isn't matching with the response coming from your provider. Set your debugger around this line https://github.com/jumbojett/OpenID-Connect-PHP/blob/ac49aba7b45063f9c05ca6c1130e5f332a148bd8/src/OpenIDConnectClient.php#L275
and step through the response. Hope this helps!

**Comment by info-kishorkunal** [comment]
Hi jumbojett, Yeah its working. Thanks a lot!!!

**Comment by jumbojett** [comment]
Glad to hear @info-kishorkunal !
